<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>

<Reference Include="Assembly-CSharp">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\ULTRAKILL_Data\Managed\Assembly-CSharp.dll</HintPath>
</Reference>

<Reference Include="BepInEx">
  <HintPath>C:\Users\chara\AppData\Roaming\r2modmanPlus-local\ULTRAKILL\profiles\Default\BepInEx\core\BepInEx.dll</HintPath>
</Reference>

<Reference Include="0Harmony">
  <HintPath>C:\Users\chara\AppData\Roaming\r2modmanPlus-local\ULTRAKILL\profiles\Default\BepInEx\core\0Harmony.dll</HintPath>
</Reference>

<Reference Include="Unity.InputSystem">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\ULTRAKILL_Data\Managed\Unity.InputSystem.dll</HintPath>
</Reference>

<Reference Include="UnityEngine">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\ULTRAKILL_Data\Managed\UnityEngine.dll</HintPath>
</Reference>

<Reference Include="UnityEngine.CoreModule">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\ULTRAKILL_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
</Reference>

<Reference Include="UnityEngine.IMGUIModule">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\ULTRAKILL_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
</Reference>

<Reference Include="UnityEngine.InputLegacyModule">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\ULTRAKILL_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
</Reference>

<Reference Include="UnityEngine.TextRenderingModule">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\ULTRAKILL_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
</Reference>

  </ItemGroup>

</Project>
