<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="UltraTasCore.cs" />

<Reference Include="BepInEx">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\Mods\ULTRAKILL\profiles\Modded\BepInEx\core\BepInEx.dll</HintPath>
</Reference>

<Reference Include="UnityEngine">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\Mods\ULTRAKILL\profiles\Modded\ULTRAKILL_Data\Managed\UnityEngine.dll</HintPath>
</Reference>

<Reference Include="UnityEngine.CoreModule">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\Mods\ULTRAKILL\profiles\Modded\ULTRAKILL_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
</Reference>

<Reference Include="UnityEngine.InputLegacyModule">
  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\ULTRAKILL\Mods\ULTRAKILL\profiles\Modded\ULTRAKILL_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
</Reference>

  </ItemGroup>

</Project>
